# Copyright © 2026 Saleem Abdulrasool <compnerd@compnerd.org>. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

add_executable(DSXTests
  BSDContinuationTests.swift
  BreakpointTableTests.swift
  ChildPortTests.swift
  DarwinEventTests.swift
  DarwinX86TrapTests.swift
  DeadlineTests.swift
  DebugControlTests.swift
  DebuggeeTests.swift
  DurationTests.swift
  ELFModuleTests.swift
  EnvironmentTests.swift
  FilePacketTests.swift
  GDBBoundaryTests.swift
  GDBEncodingTests.swift
  GDBEnvironmentPacketTests.swift
  GDBExtensionPacketTests.swift
  GDBImagePacketTests.swift
  GDBJSONTests.swift
  GDBPacketChannelTests.swift
  GDBPacketFramingTests.swift
  GDBPlatformPacketTests.swift
  GDBProcessPacketTests.swift
  GDBQueryPacketTests.swift
  GDBRegisterRequestTests.swift
  GDBRemoteTests.swift
  GDBTextTests.swift
  GDBThreadContextTests.swift
  GDBTransferEmitterTests.swift
  LaunchConfigurationTests.swift
  LazyBindingTests.swift
  LinuxARM64RegisterTests.swift
  LinuxARM64WatchpointTests.swift
  LinuxARMSyscallTests.swift
  LinuxContinuationTests.swift
  LinuxEventTests.swift
  LinuxFileSystemTests.swift
  LinuxMemoryTests.swift
  LinuxProcFSTests.swift
  LinuxProcessStatusTests.swift
  LinuxSyscallTests.swift
  LogStreamTests.swift
  MD5ChecksumTests.swift
  MachOLoadCommandTests.swift
  MachOModuleTests.swift
  MemoryPacketTests.swift
  ModuleArchitectureTests.swift
  NativeAddressTests.swift
  NativeMemoryTests.swift
  NativeParsingTests.swift
  NativeStringTests.swift
  OrderingTests.swift
  PEModuleTests.swift
  PlatformProcessesTests.swift
  PlatformServiceTests.swift
  PlatformSession+Tests.swift
  PlatformSessionTests.swift
  PlatformTests.swift
  PointerWidthTests.swift
  ProcessInfoTests.swift
  ProcessLookupTests.swift
  ProcessStartupTests.swift
  RegisterStateTests.swift
  RegisterTests.swift
  ServerTests.swift
  SignalSetTests.swift
  SignalTranslationTests.swift
  SpanSlicingTests.swift
  Support/GDBPacketHandler.swift
  Support/GDBPacketPattern.swift
  TestConnection.swift
  TransportTests.swift
  UnixCommandTests.swift
  UnixFileSystemTests.swift
  UnixHostTests.swift
  UnixMappedFileTests.swift
  UnixSpawnActionsTests.swift
  UnixSpawnTests.swift
  UnixWaitStatusTests.swift
  UnixWriteTests.swift
  WindowsBreakpointTests.swift
  WindowsContinuationTests.swift
  WindowsErrorTests.swift
  WindowsEventTests.swift
  WindowsFileSystemTests.swift
  WindowsImageTests.swift
  WindowsMemoryTests.swift
  WindowsMutexTests.swift
  WindowsPlatformProcessTests.swift
  WindowsProcessTests.swift
  WindowsStreamTests.swift
  WindowsStringTests.swift
  WindowsThreadTests.swift
  X86RegisterTests.swift)

target_link_libraries(DSXTests PRIVATE DSXCore DSXTestSupport)
dsx_test(DSXTests)
