// Copyright © 2026 Saleem Abdulrasool <compnerd@compnerd.org>. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

internal func header() -> Array<String> {
  [
    "// Copyright © 2026 Saleem Abdulrasool <compnerd@compnerd.org>. " +
        "All rights reserved.",
    "// SPDX-License-Identifier: BSD-3-Clause",
    "",
    "// Generated by DSXCodeGen. Do not edit.",
  ]
}
